# Generated by Django 6.0.6 on 2026-06-15 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('idbarcodescanner', models.CharField(max_length=100)),
                ('positionline', models.PositiveSmallIntegerField(blank=True)),
                ('positioncolumn', models.PositiveSmallIntegerField(blank=True)),
                ('positionsubposition', models.PositiveSmallIntegerField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('consumable', models.BooleanField()),
                ('image', models.ImageField(blank=True, max_length=250, upload_to='uploads/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('adress', models.CharField(blank=True, max_length=254)),
                ('zipcode', models.PositiveIntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(max_length=254)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ressourceurl', models.URLField(blank=True)),
                ('ressourcefile', models.FileField(blank=True, max_length=200, upload_to='uploads/ressources/%Y/%m/%d/')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.item')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('lines', models.PositiveSmallIntegerField(blank=True)),
                ('columns', models.PositiveSmallIntegerField(blank=True)),
                ('subpositions', models.PositiveSmallIntegerField(blank=True)),
                ('referencename', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.place')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.place'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentdate', models.DateTimeField(auto_now_add=True)),
                ('returndate', models.DateTimeField()),
                ('closedate', models.DateTimeField()),
                ('closestatus', models.CharField(choices=[('ATTENTE', 'Clôture non effectuée'), ('COMPLET', 'Retour complet'), ('FACTURE', 'Matériel Facturé (perte ou casse volontaire)'), ('CASSE', 'Matériel cassé (dans un cadre pédagogique)'), ('PROJET', 'Implanté dans un projet')], default='ATTENTE', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('renterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renterid', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('returndate', models.DateTimeField(blank=True)),
                ('returnedquantity', models.PositiveIntegerField(blank=True)),
                ('lostquantity', models.PositiveIntegerField(blank=True)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.item')),
                ('rentalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.rental')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('supplierreference', models.CharField(max_length=254)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.item')),
                ('supplierid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.suppliers')),
            ],
        ),
    ]
