# Generated by Django 6.0.6 on 2026-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_item_suppliers_characteristics_itemressource_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Homme'), (2, 'Femme')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Élève'), (2, 'Enseignant'), (3, 'Administratif')], default=1),
        ),
        migrations.AddField(
            model_name='itemressource',
            name='ressourcetype',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Documentation'), (3, 'Exemple'), (4, 'Sources')], default=1),
        ),
        migrations.AddField(
            model_name='place',
            name='placetype',
            field=models.IntegerField(choices=[(1, 'Unique'), (2, 'Ligne'), (3, 'Colonne'), (4, 'Grille')], default=1),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='supplydelay',
            field=models.IntegerField(choices=[(1, 'Rapide'), (2, 'Moyen'), (3, 'Lent')], default=3),
        ),
    ]
