# Generated by Django 6.0.6 on 2026-06-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_customuser_gender_customuser_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lines',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='subpositions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
