# Generated by Django 6.0.6 on 2026-06-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_place_columns_alter_place_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemressource',
            name='ressourcename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
