# Generated by Django 6.0.6 on 2026-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_itemressource_ressourcename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='positioncolumn',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='positionline',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='positionsubposition',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
