# Generated by Django 6.0.6 on 2026-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_alter_item_positioncolumn_alter_item_positionline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='itemsuppliers',
            name='taxes',
            field=models.IntegerField(choices=[(1, 'Ht'), (2, 'Ttc')], default=2),
        ),
        migrations.AlterField(
            model_name='itemressource',
            name='ressourcetype',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Documentation'), (3, 'Exemple'), (4, 'Sources'), (5, 'Autre')], default=1),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
