# Generated by Django 6.0.6 on 2026-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_rename_adress_suppliers_address_itemsuppliers_taxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='closedate',
            field=models.DateTimeField(blank=True),
        ),
    ]
