# Generated by Django 6.0.6 on 2026-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_alter_rental_closedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
