# Generated by Django 6.0.6 on 2026-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_place_level_place_lft_place_rght_place_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='returndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
