# Generated by Django 6.0.6 on 2026-07-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_alter_rentalitem_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='lostquantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='returnedquantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
